#!/usr/bin/env python3
"""
Interactive setup wizard for first-time configuration.

Run:  python scripts/quickstart.py

Guides you through:
  1. Polymarket wallet setup + API key generation
  2. Kalshi RSA key setup
  3. Claude API key
  4. News API keys (optional)
  5. Risk limits for your budget
  6. Writes a ready-to-use .env file
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import re
from pathlib import Path

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Confirm, FloatPrompt, Prompt
    from rich.table import Table
    from rich.text import Text
except ImportError:
    print("Run: pip install rich")
    sys.exit(1)

console = Console()

POLY_AUTH_GUIDE = """
[bold]How to get Polymarket credentials:[/bold]

1. Go to [cyan]https://polymarket.com[/cyan] and connect a wallet (MetaMask, etc.)
2. Deposit at least $5 USDC to test (you can deposit $100 later)
3. Go to [cyan]https://clob.polymarket.com[/cyan]
4. Click "Generate API Key" — this uses your wallet signature
5. Copy: API Key, Secret, Passphrase
6. Export your wallet private key from MetaMask:
   [yellow]Account Details → Export Private Key[/yellow]
   (starts with 0x...)

[red]⚠  Never share your private key with anyone.[/red]
"""

KALSHI_AUTH_GUIDE = """
[bold]How to get Kalshi API access:[/bold]

1. Go to [cyan]https://kalshi.com[/cyan] and create an account
2. Deposit funds
3. Go to [cyan]https://kalshi.com/profile/api[/cyan]
4. Add API key → upload the public key from [cyan]keys/kalshi_public.pem[/cyan]
   (run [yellow]python scripts/setup_kalshi_keys.py[/yellow] first)
5. Copy the Key ID shown after upload

For demo/testing: use [cyan]https://demo.kalshi.co[/cyan] (no real money)
"""

CLAUDE_GUIDE = """
[bold]How to get Claude API key:[/bold]

1. Go to [cyan]https://console.anthropic.com[/cyan]
2. Create an account and add a payment method
3. Go to API Keys → Create Key
4. Copy the key (starts with [yellow]sk-ant-...[/yellow])

Cost estimate for $100 trading budget:
  ~$2–5/month at 60-second cycle intervals
"""


def section(title: str) -> None:
    console.print()
    console.rule(f"[bold cyan]{title}[/bold cyan]")
    console.print()


def write_env(config: dict, path: Path) -> None:
    lines = [
        "# Generated by quickstart.py — edit freely",
        "",
        "# ---- Global ----",
        f"MOCK_MODE={str(config.get('mock_mode', True)).lower()}",
        "",
        "# ---- Claude / Anthropic ----",
        f"ANTHROPIC_API_KEY={config.get('anthropic_key', '')}",
        "",
        "# ---- Polymarket ----",
        f"POLY_PRIVATE_KEY={config.get('poly_pk', '')}",
        f"POLY_API_KEY={config.get('poly_api_key', '')}",
        f"POLY_API_SECRET={config.get('poly_api_secret', '')}",
        f"POLY_API_PASSPHRASE={config.get('poly_api_pass', '')}",
        f"POLY_CHAIN_ID={config.get('chain_id', 137)}",
        "POLY_CLOB_HOST=https://clob.polymarket.com",
        "POLY_GAMMA_HOST=https://gamma-api.polymarket.com",
        "",
        "# ---- Kalshi ----",
        f"KALSHI_API_KEY_ID={config.get('kalshi_key_id', '')}",
        f"KALSHI_PRIVATE_KEY_PATH={config.get('kalshi_key_path', 'keys/kalshi_private.pem')}",
        f"KALSHI_DEMO_MODE={str(config.get('kalshi_demo', True)).lower()}",
        "KALSHI_API_HOST=https://api.elections.kalshi.com",
        "",
        "# ---- Risk (tuned for ${budget} budget) ----".replace("${budget}", str(config.get('budget', 100))),
        f"RISK_MAX_POSITION_SIZE_USD={config.get('max_position', 10)}",
        f"RISK_MAX_PORTFOLIO_EXPOSURE_USD={config.get('max_exposure', 80)}",
        f"RISK_DAILY_LOSS_LIMIT_USD={config.get('daily_loss_limit', 20)}",
        f"RISK_STOP_LOSS_PCT={config.get('stop_loss_pct', 0.30)}",
        f"RISK_TAKE_PROFIT_PCT={config.get('take_profit_pct', 0.80)}",
        f"RISK_MIN_EDGE_PCT={config.get('min_edge', 0.05)}",
        f"RISK_MAX_KELLY_FRACTION={config.get('kelly_fraction', 0.15)}",
        f"RISK_MIN_CONFIDENCE_SCORE={config.get('min_confidence', 0.65)}",
        "",
        "# ---- News (optional but improves signals) ----",
        f"NEWS_TAVILY_API_KEY={config.get('tavily_key', '')}",
        f"NEWS_NEWSAPI_KEY={config.get('newsapi_key', '')}",
        "",
        "# ---- Bot ----",
        f"BOT_CYCLE_INTERVAL_SECONDS={config.get('cycle_interval', 60)}",
        "BOT_LOG_LEVEL=INFO",
        f"BOT_ENABLE_ARBITRAGE={str(config.get('enable_arb', True)).lower()}",
        f"BOT_ENABLE_POLYMARKET={str(config.get('enable_poly', True)).lower()}",
        f"BOT_ENABLE_KALSHI={str(config.get('enable_kalshi', False)).lower()}",
    ]
    path.write_text("\n".join(lines) + "\n")


def compute_risk_limits(budget: float) -> dict:
    """Conservative risk limits scaled to budget."""
    return {
        "max_position": round(budget * 0.10, 2),   # 10% per trade
        "max_exposure": round(budget * 0.80, 2),   # 80% max deployed
        "daily_loss_limit": round(budget * 0.20, 2), # 20% max daily loss
        "stop_loss_pct": 0.30,
        "take_profit_pct": 0.80,
        "min_edge": 0.05,
        "kelly_fraction": 0.15,     # conservative 15% Kelly for small accounts
        "min_confidence": 0.65,
    }


def main() -> None:
    console.print(Panel.fit(
        "[bold green]Polymarket + Kalshi AI Bot Setup Wizard[/bold green]\n"
        "This will create a [cyan].env[/cyan] file with your credentials.\n"
        "You can re-run this anytime to update settings.",
        title="🤖 Setup",
    ))

    config: dict = {}

    # ----------------------------------------------------------------
    section("1. Trading Budget")
    budget = FloatPrompt.ask(
        "What is your total trading budget in USD?",
        default=100.0,
    )
    config["budget"] = budget
    config.update(compute_risk_limits(budget))

    risk_table = Table(title=f"Suggested risk limits for ${budget:.0f} budget", show_lines=True)
    risk_table.add_column("Setting")
    risk_table.add_column("Value", justify="right")
    risk_table.add_column("Meaning")
    risk_table.add_row("Max position size", f"${config['max_position']}", "Max per single trade")
    risk_table.add_row("Max total exposure", f"${config['max_exposure']}", "Max deployed at once")
    risk_table.add_row("Daily loss limit", f"${config['daily_loss_limit']}", "Bot halts if hit")
    risk_table.add_row("Stop-loss", f"{config['stop_loss_pct']:.0%}", "Auto-exit on loss")
    risk_table.add_row("Take-profit", f"{config['take_profit_pct']:.0%}", "Auto-exit on gain")
    risk_table.add_row("Kelly fraction", f"{config['kelly_fraction']:.0%}", "Position sizing safety")
    console.print(risk_table)

    customize = Confirm.ask("Customize these limits?", default=False)
    if customize:
        config["max_position"] = FloatPrompt.ask("Max position size (USD)", default=config["max_position"])
        config["daily_loss_limit"] = FloatPrompt.ask("Daily loss limit (USD)", default=config["daily_loss_limit"])
        config["stop_loss_pct"] = FloatPrompt.ask("Stop-loss % (e.g. 0.30 = 30%)", default=config["stop_loss_pct"])

    # ----------------------------------------------------------------
    section("2. Mock Mode")
    console.print(
        "[yellow]Mock mode = ON means the bot analyses markets and prints signals "
        "but places NO real orders.[/yellow]\n"
        "Always start with mock mode to verify everything works."
    )
    mock_mode = Confirm.ask("Start in mock mode (recommended)?", default=True)
    config["mock_mode"] = mock_mode
    if not mock_mode:
        console.print(
            "[bold red]⚠  Live trading enabled. Real money will be used.\n"
            "Make sure you've tested in mock mode for at least a few days.[/bold red]"
        )

    # ----------------------------------------------------------------
    section("3. Claude API Key")
    console.print(CLAUDE_GUIDE)
    anthropic_key = Prompt.ask(
        "Anthropic API key (sk-ant-...)", default="", password=True
    )
    config["anthropic_key"] = anthropic_key

    # ----------------------------------------------------------------
    section("4. Polymarket Credentials")
    enable_poly = Confirm.ask("Enable Polymarket trading?", default=True)
    config["enable_poly"] = enable_poly
    if enable_poly:
        console.print(POLY_AUTH_GUIDE)
        config["poly_pk"] = Prompt.ask("Wallet private key (0x...)", default="", password=True)
        config["poly_api_key"] = Prompt.ask("Polymarket API key", default="")
        config["poly_api_secret"] = Prompt.ask("Polymarket API secret", default="", password=True)
        config["poly_api_pass"] = Prompt.ask("Polymarket API passphrase", default="", password=True)
        testnet = Confirm.ask("Use Amoy testnet (no real money)?", default=False)
        config["chain_id"] = 80002 if testnet else 137

    # ----------------------------------------------------------------
    section("5. Kalshi Credentials (optional)")
    enable_kalshi = Confirm.ask("Enable Kalshi trading?", default=False)
    config["enable_kalshi"] = enable_kalshi
    if enable_kalshi:
        console.print(KALSHI_AUTH_GUIDE)
        keys_exist = Path("keys/kalshi_private.pem").exists()
        if not keys_exist:
            gen_keys = Confirm.ask("Generate Kalshi RSA keys now?", default=True)
            if gen_keys:
                import subprocess
                subprocess.run([sys.executable, "scripts/setup_kalshi_keys.py"])
        config["kalshi_key_id"] = Prompt.ask("Kalshi API Key ID", default="")
        config["kalshi_key_path"] = Prompt.ask("Kalshi private key path", default="keys/kalshi_private.pem")
        config["kalshi_demo"] = Confirm.ask("Use Kalshi demo environment?", default=True)

    # ----------------------------------------------------------------
    section("6. News API Keys (optional — improves signal quality)")
    setup_news = Confirm.ask("Configure news API keys?", default=False)
    if setup_news:
        console.print("[dim]Tavily: https://tavily.com  |  NewsAPI: https://newsapi.org[/dim]")
        config["tavily_key"] = Prompt.ask("Tavily API key (tvly-...)", default="")
        config["newsapi_key"] = Prompt.ask("NewsAPI key", default="")

    # ----------------------------------------------------------------
    section("7. Cycle Interval")
    interval = Prompt.ask(
        "How often to scan markets? (seconds, default 60)",
        default="60",
    )
    config["cycle_interval"] = int(interval)

    # ----------------------------------------------------------------
    section("8. Write .env")
    env_path = Path(".env")
    if env_path.exists():
        overwrite = Confirm.ask(".env already exists. Overwrite?", default=True)
        if not overwrite:
            env_path = Path(".env.new")
            console.print(f"[dim]Writing to {env_path} instead[/dim]")

    write_env(config, env_path)
    console.print(f"[green]✓ Written to {env_path}[/green]")

    # ----------------------------------------------------------------
    console.print()
    console.print(Panel.fit(
        f"[bold green]Setup complete![/bold green]\n\n"
        f"Budget: [cyan]${budget:.0f}[/cyan]  "
        f"Mock mode: [{'yellow' if config['mock_mode'] else 'red'}]{config['mock_mode']}[/{'yellow' if config['mock_mode'] else 'red'}]\n\n"
        f"[bold]Run the bot:[/bold]\n"
        f"  [cyan]python main.py[/cyan]          ← unified (both platforms)\n"
        f"  [cyan]python -m polymarket_bot.main[/cyan]  ← Polymarket only\n"
        f"  [cyan]python -m kalshi_bot.main[/cyan]      ← Kalshi only\n\n"
        f"[bold]Run backtest first:[/bold]\n"
        f"  [cyan]python scripts/run_backtest.py --source mock --n 500[/cyan]\n\n"
        f"[dim]Tip: Set MOCK_MODE=false only after testing for several days.[/dim]",
        title="✅ Ready",
    ))


if __name__ == "__main__":
    main()
